const fs=require('fs'), vm=require('vm');
const html=fs.readFileSync('index.html','utf8');
const m=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)];
let code=m.map(s=>s[1]).join('\n');
code=code.replace(/\ninit\(\);\s*\n/, '\n'); // skip auto init in test
const fakeEl={innerHTML:'',classList:{add(){},remove(){}},textContent:'',dataset:{},addEventListener(){},querySelector(){return null},querySelectorAll(){return []},style:{}};
const document={getElementById:()=>fakeEl,addEventListener(){},createElement:()=>({style:{},appendChild(){},select(){},setAttribute(){}}),body:{appendChild(){},removeChild(){}},querySelector(){return null},querySelectorAll(){return []}};
const window={addEventListener(){}};
const navigator={clipboard:{writeText:()=>Promise.resolve()}};
const localStorage={getItem:()=>null,setItem(){},removeItem(){}};
const fetch=()=>Promise.reject(new Error('no net'));
const ctx={document,window,navigator,localStorage,fetch,AbortController,setTimeout,clearTimeout,setInterval,console,Math,Date,JSON,Promise,RegExp,parseInt,parseFloat,isNaN};
ctx.globalThis=ctx;
vm.createContext(ctx);
vm.runInContext(code+'\n;renderView=function(){};globalThis.__api={ui,renderReading,readingIndices,readingQuizHTML,handleAct,READINGS};', ctx);
const A=ctx.__api;
let pass=true;
A.ui.readFilter='TED';
const pool=A.readingIndices();
console.log('TED pool size:', pool.length, pool.length===8?'(OK 8篇)':'(FAIL)'); if(pool.length!==8) pass=false;
const out=A.renderReading();
const tedTitles=A.READINGS.filter(r=>r.src==='TED').map(r=>r.title);
const showsTed=tedTitles.some(t=>out.includes(t));
console.log('TED view shows a TED article:', showsTed, showsTed?'OK':'FAIL'); if(!showsTed) pass=false;
console.log('has filter chips (readFilter):', out.includes('data-act="readFilter"')?'OK':'FAIL'); if(!out.includes('data-act="readFilter"')) pass=false;
console.log('has quiz buttons (readQuiz):', out.includes('data-act="readQuiz"')?'OK':'FAIL'); if(!out.includes('data-act="readQuiz"')) pass=false;
const r=A.READINGS[pool[0]];
const q1=A.readingQuizHTML(r), q2=A.readingQuizHTML(r);
console.log('quiz deterministic (same each render):', q1===q2?'OK':'FAIL'); if(q1!==q2) pass=false;
const qCount=(q1.match(/class="rq-q"/g)||[]).length;
console.log('quiz question count:', qCount, qCount===2?'(OK 2题)':'(FAIL)'); if(qCount!==2) pass=false;
const key=r.title;
try{ A.handleAct('readQuiz', {dataset:{key, q:'0', opt:'0'}}); }catch(e){ console.log('handleAct readQuiz THREW:', e.message); pass=false; }
console.log('after click ui.readQuiz[key][0] set:', (A.ui.readQuiz[key]&&A.ui.readQuiz[key][0]!==null)?'OK':'FAIL');
if(!(A.ui.readQuiz[key]&&A.ui.readQuiz[key][0]!==null)) pass=false;
const before=A.ui.readQuiz[key][0];
A.handleAct('readQuiz', {dataset:{key, q:'0', opt:'3'}});
console.log('re-click same question ignored:', A.ui.readQuiz[key][0]===before?'OK':'FAIL'); if(A.ui.readQuiz[key][0]!==before) pass=false;
A.ui.readFilter='all';
const outAll=A.renderReading();
console.log('all view has filter chips:', outAll.includes('data-act="readFilter"')?'OK':'FAIL'); if(!outAll.includes('data-act="readFilter"')) pass=false;
console.log(pass?'\n=== READ DEBUG ALL PASS ===':'\n=== READ DEBUG HAS FAILURES ===');
